name: Security

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run security checks daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.0

    - name: Set up Go
      uses: actions/setup-go@v6.0.0
      with:
        go-version: '1.24'

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Run govulncheck
      run: govulncheck ./...

  nancy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.0

    - name: Set up Go
      uses: actions/setup-go@v6.0.0
      with:
        go-version: '1.24'

    - name: WriteGoList
      run: go list -json -m all > go.list

    - name: Nancy
      uses: sonatype-nexus-community/nancy-github-action@main
      with:
        nancyCommand: sleuth --loud

  gosec:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    env:
      GO111MODULE: on
    steps:
    - name: Checkout Source
      uses: actions/checkout@v5.0.0

    - name: Set up Go
      uses: actions/setup-go@v6.0.0
      with:
        go-version: '1.24'

    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        # we let the report trigger content trigger a failure using the GitHub Security features.
        args: '-no-fail -fmt sarif -out results.sarif ./...'

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@codeql-bundle-v2.23.0
      with:
        sarif_file: results.sarif

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'go' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5.0.0

    - name: Initialize CodeQL
      uses: github/codeql-action/init@codeql-bundle-v2.23.0
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@codeql-bundle-v2.23.0

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@codeql-bundle-v2.23.0
      with:
        category: "/language:${{matrix.language}}"
